# Generated by Django 5.2.8 on 2025-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_articulo_editor_alter_articulo_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='media/post_default.png', null=True, upload_to='media'),
        ),
    ]
